# Generated by Django 2.0.5 on 2018-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhuceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usersmt',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
